      - name: Print last 5 devices
        run: |
          python -c "
import json
from datetime import datetime
with open('taf_5g_products.json', encoding='utf-8') as f:
    d = json.load(f)
try:
    # Adjust the date format below if needed!
    d_sorted = sorted(d, key=lambda x: datetime.strptime(x[-1].strip(), '%Y-%m-%d'), reverse=True)
    for prod in d_sorted[:5]:
        print(prod)
        print()
except Exception as e:
    print('Error sorting products by date:', e)
    for prod in d[-5:]:
        print(prod)
        print()
"
